/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.qlthuvien.view;

import com.mycompany.qlthuvien.DatabaseConnection;
import com.mycompany.qlthuvien.dao.MemberDao;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author minh9
 */
public class MemberForm extends javax.swing.JFrame {

    /**
     * Creates new form MemberForm
     */
    public MemberForm() {
        initComponents();
        MemberDao memberDao = new MemberDao(jMemTable);
        memberDao.showMem();
        getContentPane().setBackground(Color.decode("#FFF7FC"));
        DefaultTableCellRenderer head_render = new DefaultTableCellRenderer();
        head_render.setForeground(Color.white);
        head_render.setBackground(Color.decode("#5755FE"));
        jMemTable.getTableHeader().setDefaultRenderer(head_render);
        jMemTable.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        setLocationRelativeTo(null); // Hiển thị form ở giữa màn hình
        memLbl.setHorizontalAlignment(JLabel.CENTER);
        memLbl.setVerticalAlignment(JLabel.CENTER);
        memLbl.setPreferredSize(new Dimension(0, 100));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jFrame1 = new javax.swing.JFrame();
        memLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        searchTXT = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jMemTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        maMemTXT = new javax.swing.JLabel();
        tenMemTXT = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        genderMemTXT = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        changeMemBtn = new javax.swing.JButton();
        deleteMemBtn = new javax.swing.JButton();
        addMemBtn = new javax.swing.JButton();
        memAva = new javax.swing.JLabel();
        outBtn = new javax.swing.JButton();
        undoMemBtn = new javax.swing.JButton();
        RedoMemBtn = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        jCheckBox1.setText("jCheckBox1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(248, 237, 237));

        memLbl.setBackground(new java.awt.Color(255, 103, 102));
        memLbl.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        memLbl.setForeground(new java.awt.Color(255, 255, 255));
        memLbl.setText("DANH SÁCH ĐỘC GIẢ");
        memLbl.setOpaque(true);
        memLbl.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Tìm kiếm member");

        searchTXT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        searchTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTXTActionPerformed(evt);
            }
        });

        searchBtn.setBackground(new java.awt.Color(0, 0, 0));
        searchBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jMemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MaDocGia", "TenDocGia", "NgaySinh", "Email", "NgayLapThe", "NgayHetHan", "TrangThaiThe", "GioiTinh"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jMemTable.setFocusable(false);
        jMemTable.setGridColor(new java.awt.Color(128, 128, 128));
        jMemTable.setRowHeight(25);
        jMemTable.setSelectionBackground(new java.awt.Color(255, 102, 102));
        jMemTable.setShowHorizontalLines(true);
        jMemTable.getTableHeader().setReorderingAllowed(false);
        jMemTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMemTableMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMemTableMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(jMemTable);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Mã độc giả:");

        maMemTXT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        maMemTXT.setText("....");

        tenMemTXT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tenMemTXT.setText("....");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Tên độc giả:");

        genderMemTXT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        genderMemTXT.setText("....");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Giới tính:");

        changeMemBtn.setBackground(new java.awt.Color(0, 204, 0));
        changeMemBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        changeMemBtn.setForeground(new java.awt.Color(255, 255, 255));
        changeMemBtn.setText("Sửa");
        changeMemBtn.setBorder(null);
        changeMemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeMemBtnActionPerformed(evt);
            }
        });

        deleteMemBtn.setBackground(new java.awt.Color(255, 69, 0));
        deleteMemBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        deleteMemBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteMemBtn.setText("Xóa");
        deleteMemBtn.setBorder(null);
        deleteMemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMemBtnActionPerformed(evt);
            }
        });

        addMemBtn.setBackground(new java.awt.Color(153, 153, 255));
        addMemBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        addMemBtn.setForeground(new java.awt.Color(255, 255, 255));
        addMemBtn.setText("Thêm ");
        addMemBtn.setBorder(null);
        addMemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemBtnActionPerformed(evt);
            }
        });

        memAva.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        outBtn.setBackground(new java.awt.Color(0, 0, 153));
        outBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        outBtn.setForeground(new java.awt.Color(255, 255, 255));
        outBtn.setText("Thoát");
        outBtn.setBorder(null);
        outBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outBtnActionPerformed(evt);
            }
        });

        undoMemBtn.setBackground(new java.awt.Color(255, 51, 255));
        undoMemBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        undoMemBtn.setForeground(new java.awt.Color(255, 255, 255));
        undoMemBtn.setText("Undo");
        undoMemBtn.setBorder(null);
        undoMemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoMemBtnActionPerformed(evt);
            }
        });

        RedoMemBtn.setBackground(new java.awt.Color(255, 51, 255));
        RedoMemBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        RedoMemBtn.setForeground(new java.awt.Color(255, 255, 255));
        RedoMemBtn.setText("Redo");
        RedoMemBtn.setBorder(null);
        RedoMemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RedoMemBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(memLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(memAva, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6))
                            .addComponent(jLabel3))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tenMemTXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(maMemTXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(genderMemTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(searchTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(searchBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addMemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(changeMemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(RedoMemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(undoMemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deleteMemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(outBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(memLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(memAva, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(maMemTXT)
                                .addGap(18, 18, 18)
                                .addComponent(tenMemTXT)
                                .addGap(18, 18, 18)
                                .addComponent(genderMemTXT))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteMemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeMemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addMemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(undoMemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RedoMemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTXTActionPerformed

    private void addMemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemBtnActionPerformed
        // TODO add your handling code here:
        RegisterMember registerMember = new RegisterMember(jMemTable);
        registerMember.setVisible(true);

    }//GEN-LAST:event_addMemBtnActionPerformed

    private void changeMemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeMemBtnActionPerformed
        // TODO add your handling code here:
        UpdateMem updateMem = new UpdateMem(jMemTable);
        updateMem.setVisible(true);
    }//GEN-LAST:event_changeMemBtnActionPerformed

    private void jMemTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMemTableMouseClicked
        // TODO add your handling code here:
        int j = jMemTable.getSelectedRow();
        TableModel model = jMemTable.getModel();
        maMemTXT.setText(model.getValueAt(j, 0).toString());
        tenMemTXT.setText(model.getValueAt(j, 1).toString());
        genderMemTXT.setText(model.getValueAt(j, 7).toString());
        String maDocGia = model.getValueAt(j, 0).toString();
        DatabaseConnection dbConnection = DatabaseConnection.getInstance();
        Connection connection = dbConnection.getConnection();
        String sql = "SELECT Hinh FROM DocGia WHERE MaDocGia = ?";
        try (PreparedStatement ps = connection.prepareStatement(sql)) {
            ps.setString(1, maDocGia);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                byte[] img = rs.getBytes("Hinh");
                if (img != null) {
                    ImageIcon image = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(memAva.getWidth(), memAva.getHeight(), Image.SCALE_SMOOTH));
                    memAva.setIcon(image);
                    System.out.println("Image loaded for MaDocGia: " + maDocGia);
                } else {
                    memAva.setIcon(null);
                    System.out.println("No image found for MaDocGia: " + maDocGia);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jMemTableMouseClicked

    private void deleteMemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMemBtnActionPerformed
        // TODO add your handling code here:
        MemberDao memberDao = new MemberDao(jMemTable);
        int i = JOptionPane.showConfirmDialog(null, "Bạn có chắn chắn muốn xóa", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (i == 0) {
            memberDao.deleteMem();
        }
    }//GEN-LAST:event_deleteMemBtnActionPerformed

    private void jMemTableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMemTableMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_jMemTableMouseExited

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        String srch = searchTXT.getText();
        DatabaseConnection dbConnection = DatabaseConnection.getInstance();;
        Connection connection = dbConnection.getConnection();
        String sql = "Select * from DocGia where MaDocGia like N'%" + srch + "%' or HoTen like N'%" + srch + "%' ";
        try (PreparedStatement ps = connection.prepareStatement(sql)) {
            ResultSet rs = ps.executeQuery();
            //  jMemTable.setModel(DbUtils.resultSetToTableModel(rs));
            // Create a DefaultTableModel
            DefaultTableModel tableModel = new DefaultTableModel();
            ResultSetMetaData metaData = rs.getMetaData();
            System.out.println("");
            // Add column names
            int columnCount = metaData.getColumnCount();
            for (int i = 1; i < columnCount; i++) {
                tableModel.addColumn(metaData.getColumnName(i));
            }
            // Add rows
            Object[] row = new Object[columnCount];
            while (rs.next()) {
                for (int i = 1; i <= columnCount; i++) {
                    row[i - 1] = rs.getObject(i);
                }
                tableModel.addRow(row);
            }
            jMemTable.setModel(tableModel);
            // Set the model

            System.out.println("Tim thanh cong");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void outBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outBtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_outBtnActionPerformed

    private void undoMemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoMemBtnActionPerformed
        MemberDao memberDao = new MemberDao(jMemTable);
        try {
            memberDao.restoreMem();
             DefaultTableModel model = (DefaultTableModel) jMemTable.getModel();
             model.setRowCount(0);
             memberDao.showMem();

        } catch (SQLException ex) {
            Logger.getLogger(MemberForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_undoMemBtnActionPerformed

    private void RedoMemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RedoMemBtnActionPerformed
        // TODO add your handling code here:
        
        MemberDao memberDao = new MemberDao(jMemTable);
        try {
            memberDao.resetMem();
             DefaultTableModel model = (DefaultTableModel) jMemTable.getModel();
             model.setRowCount(0);
             memberDao.showMem();
        } catch (SQLException ex) {
            Logger.getLogger(MemberForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RedoMemBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RedoMemBtn;
    private javax.swing.JButton addMemBtn;
    private javax.swing.JButton changeMemBtn;
    private javax.swing.JButton deleteMemBtn;
    private javax.swing.JLabel genderMemTXT;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTable jMemTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel maMemTXT;
    private javax.swing.JLabel memAva;
    private javax.swing.JLabel memLbl;
    private javax.swing.JButton outBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTXT;
    private javax.swing.JLabel tenMemTXT;
    private javax.swing.JButton undoMemBtn;
    // End of variables declaration//GEN-END:variables
}
