/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.qlthuvien.view;

import com.mycompany.qlthuvien.dao.MemberDao;
import com.mycompany.qlthuvien.model.Member;
import java.awt.Color;
import java.awt.Image;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.text.DateFormat;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author minh9
 */
public class RegisterMember extends javax.swing.JFrame {

    /**
     * Creates new form RegisterMember
     */
    String fileName = null;
    byte[] memImage = null;
    private JTable jMemTable;

    public RegisterMember(JTable jMemTable) {
        this.jMemTable = jMemTable;
        getContentPane().setBackground(Color.decode("#FFF7FC"));
        initComponents();
        setLocationRelativeTo(null); // Hiển thị form ở giữa màn hình

    }

    private boolean validation() {
        Date selectedCreDate = (Date) createDob.getDate();
        Date selectedExDate = (Date) expiryDob.getDate();
        LocalDate currentDate = LocalDate.now();
        ///CreDate
        Instant instantCre = selectedCreDate.toInstant();
        ZonedDateTime zonedDateTime = instantCre.atZone(ZoneId.systemDefault());
        LocalDate creLocal = zonedDateTime.toLocalDate();
        ///ExDate
        Instant instantEx = selectedExDate.toInstant();
        ZonedDateTime exTime = instantEx.atZone(ZoneId.systemDefault());
        LocalDate exLocal = exTime.toLocalDate();
        //////
        if (creLocal.isAfter(currentDate) || creLocal.isBefore(currentDate)) {
            JOptionPane.showMessageDialog(null, "Ngày tạo thẻ không hợp lệ", "Lỗi", JOptionPane.ERROR_MESSAGE);
            createDob.setDate(selectedCreDate);
            return false;
        }
        if (exLocal.isBefore(creLocal)) {
            JOptionPane.showMessageDialog(null, "Ngày hết hạn không hợp lệ", "Lỗi", JOptionPane.ERROR_MESSAGE);
            expiryDob.setDate(null);
            return false;
        }
        if (nameTXT.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tên không được để trống", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (emailTXT.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Email không được để trống", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jFileChooser1 = new javax.swing.JFileChooser();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameTXT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        birthDob = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        emailTXT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        createDob = new com.toedter.calendar.JDateChooser();
        btnAdd = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbGender = new javax.swing.JComboBox<>();
        imageChooseBtn = new javax.swing.JButton();
        memAvatar = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        expiryDob = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        btnOut = new javax.swing.JButton();

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Ngày sinh");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 247, 252));

        jLabel1.setBackground(new java.awt.Color(255, 103, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thêm Member");
        jLabel1.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Họ và tên");

        nameTXT.setBackground(new java.awt.Color(245, 247, 248));
        nameTXT.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        nameTXT.setPreferredSize(new java.awt.Dimension(65, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Ngày sinh");

        birthDob.setBackground(new java.awt.Color(245, 247, 248));
        birthDob.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        birthDob.setPreferredSize(new java.awt.Dimension(65, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Email");

        emailTXT.setBackground(new java.awt.Color(245, 247, 248));
        emailTXT.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        emailTXT.setPreferredSize(new java.awt.Dimension(65, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Ngày lập thẻ");

        createDob.setBackground(new java.awt.Color(245, 247, 248));
        createDob.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N

        btnAdd.setBackground(new java.awt.Color(102, 102, 255));
        btnAdd.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Thêm");
        btnAdd.setBorder(null);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Giới tính");

        cbGender.setBackground(new java.awt.Color(245, 247, 248));
        cbGender.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        cbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cbGender.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGenderActionPerformed(evt);
            }
        });

        imageChooseBtn.setBackground(new java.awt.Color(255, 153, 51));
        imageChooseBtn.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        imageChooseBtn.setForeground(new java.awt.Color(255, 255, 255));
        imageChooseBtn.setText("Chọn ảnh");
        imageChooseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageChooseBtnActionPerformed(evt);
            }
        });

        memAvatar.setBackground(new java.awt.Color(255, 255, 255));
        memAvatar.setForeground(new java.awt.Color(255, 255, 255));
        memAvatar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Ngày hết hạn");

        expiryDob.setBackground(new java.awt.Color(245, 247, 248));
        expiryDob.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Trạng thái");

        cbStatus.setBackground(new java.awt.Color(245, 247, 248));
        cbStatus.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1" }));
        cbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStatusActionPerformed(evt);
            }
        });

        btnOut.setBackground(new java.awt.Color(255, 0, 51));
        btnOut.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btnOut.setForeground(new java.awt.Color(255, 255, 255));
        btnOut.setText("Thoát");
        btnOut.setBorder(null);
        btnOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(birthDob, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emailTXT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(createDob, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(expiryDob, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbGender, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameTXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(memAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(imageChooseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(birthDob, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createDob, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(expiryDob, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(cbGender, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(memAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageChooseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOut, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        btnAdd.getAccessibleContext().setAccessibleParent(btnAdd);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        int s = 0;
        MemberDao memberDao = new MemberDao(jMemTable);
        String g = cbGender.getSelectedItem().toString();
        if (validation()) {
            int n = 0;
            if (g == "Nam") {
                n = 0;
            } else {
                n = 1;
            }
            Date bdob = birthDob.getDate();
            if (bdob == null) {
                JOptionPane.showMessageDialog(null, "Date of Birth is empty");
                return;
            }
            Date cdob = createDob.getDate();
            if (cdob == null) {
                JOptionPane.showMessageDialog(null, "Create Date is empty");
                return;
            }
            Date edob = expiryDob.getDate();
            if (edob == null) {
                JOptionPane.showMessageDialog(null, "Expiry Date is empty");
                return;
            }
            String trangThai = cbStatus.getSelectedItem().toString();
            System.out.println(" name: " + nameTXT.getText() + "birthDate: " + DateFormat.getDateInstance(DateFormat.DEFAULT).format(bdob) + " createDate: " + DateFormat.getDateInstance(DateFormat.DEFAULT).format(cdob)
                    + " expiryDate: " + DateFormat.getDateInstance(DateFormat.DEFAULT).format(edob) + " Email: " + emailTXT.getText() + " gender: " + n + " trang thai: " + trangThai + " hinh " + memImage);
            Member member = new Member(null, nameTXT.getText(), bdob, emailTXT.getText(), cdob, edob, trangThai, n, memImage);
            memberDao = new MemberDao(jMemTable);
            memberDao.addMem(member);
            s = 1;
        }
        DefaultTableModel model = (DefaultTableModel) jMemTable.getModel();
        model.setRowCount(0);
        memberDao.showMem();
        if (s == 1) {
            JOptionPane.showMessageDialog(null, "Register successfully");
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Register failed");
        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void cbGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGenderActionPerformed

    private void imageChooseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageChooseBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser(); //khoi tao JFileChooser
        chooser.showOpenDialog(null); //Mo bang chon file
        File f = chooser.getSelectedFile();
        fileName = f.getAbsolutePath(); //gán đường dẫn của file
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(fileName).getImage().getScaledInstance(memAvatar.getWidth(), memAvatar.getHeight(), Image.SCALE_SMOOTH)); //Tạo image icon dựa trên đường dẫn filename
        memAvatar.setIcon(imageIcon); //set hinh anh cho lable
        try {
            File image = new File(fileName); //Tạo file cho hình ảnh đã chọn
            FileInputStream fileInputStream = new FileInputStream(image); //Đọc file
            ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream(); //tạo biến byte để lưu dữ liệu của hình ảnh
            byte[] buf = new byte[1024];    // Tạo bộ đệm để đọc từng khối dữ liệu của tệp ChatGPT :))
            for (int readNum; (readNum = fileInputStream.read(buf)) != -1;) {
                byteArrayOutputStream.write(buf, 0, readNum); //ghi file đã đọc vào biến đã tạo
            }
            memImage = byteArrayOutputStream.toByteArray();//chuyển đổi biến đã tạo thành mảng byte
        } catch (Exception e) {

        }
    }//GEN-LAST:event_imageChooseBtnActionPerformed

    private void cbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStatusActionPerformed

    private void btnOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.toedter.calendar.JDateChooser birthDob;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnOut;
    public javax.swing.JComboBox<String> cbGender;
    public javax.swing.JComboBox<String> cbStatus;
    public com.toedter.calendar.JDateChooser createDob;
    public javax.swing.JTextField emailTXT;
    public com.toedter.calendar.JDateChooser expiryDob;
    private javax.swing.JButton imageChooseBtn;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel memAvatar;
    public javax.swing.JTextField nameTXT;
    // End of variables declaration//GEN-END:variables
}
